---
title: "R Notebook"
output: html_notebook
---


## Preliminares

```{r}
library(tidyverse)
library(magrittr)
library(skimr)
```

### Importacion

```{r}
data <- read_csv('Data/Churn_Modelling.csv')
```
#### Verificar y corregir columnas

```{r}
data %>% glimpse
```

```{r}
data %>% 
  mutate(
    HasCrCard= factor(HasCrCard, levels= c(0, 1), 
                             labels= c('no', 'si') ),
    IsActiveMember= factor(IsActiveMember, levels= c(0, 1), 
                             labels= c('no', 'si') ),
    
  ) ->
  data
```

```{r}
data %>% glimpse
```


# EDA

## EDA Univariado

```{r}
skim( data)
```




```{r}
data %>% 
  reframe( 
    tibble(
      Descrip= c('P_0', 'P_02', 'P_25', 'P_50' , 'P_75', 'P_98', 'P_100') ,
      Valor= quantile( Balance, c(0, 0.2, 0.25, 0.50 ,0.75, 0.98, 1), na.rm= T)
    )
    )
```


```{r}
data %>% 
  reframe( 
    tibble(
      Descrip= c('P_0', 'P_02', 'P_25', 'P_50' , 'P_75', 'P_97', 'P_100') ,
      Valor= quantile( CreditScore, c(0, 0.2, 0.25, 0.50 ,0.75, 0.97, 1), na.rm= T)
    )
    )
```

```{r}
data %>% 
  group_by(Exited) %>% 
  count()
```

```{r}
data %>% 
  group_by(Exited) %>% 
  count() %>% 
  ggplot( aes(x= Exited, y= n)) +
  geom_col()
```


## EDA Multivariado

### Room 11

#### CreditScore vs Exited

**Tabla**
```{r}

```

**Grafico**
```{r}

```

**Interpretacion**





### Room 14

#### Balance vs Exited

**Tabla**
Descriptivos
```{r warning=FALSE}
library(doBy)
library(DescTools)

data_r14 <- data %>% 
  mutate(
    Exited= factor(Exited, levels= c(0, 1),labels=c("no","si")))
  
cuartil_25 <- function(x) {
  q25 <- quantile(x, 0.25, na.rm = TRUE)
  return(cuartil = q25)
}

cuartil_75 <- function(x) {
  q75 <- quantile(x, 0.75, na.rm = TRUE)
  return(cuartil = q75)
}

summaryBy(
  Balance ~ Exited,
  data = data_r14,
  FUN = c(mean, Mode, cuartil_25, median, cuartil_75, sd, min, max)
)

```


Correlación de Spearman
```{r warning=FALSE}
cor(data_r14$Balance,as.numeric(data_r14$Exited))
```
Correlación Point-Biseral
```{r warning=FALSE}
library(polycor)
polyserial(data_r14$Balance,data_r14$Exited)
```

**Grafico**
Densidad
```{r}
library(ggplot2)
data_r14 %>% 
  ggplot(aes(x=Balance, fill=Exited))+
  geom_density()+
  theme_bw()+
  facet_grid(. ~ Exited)
```
Densidad
```{r}
library(ggplot2)
data_r14 %>% 
  ggplot(aes(x=Balance, fill=Exited))+
  geom_boxplot()+
  theme_bw()+
  facet_grid(. ~ Exited)
```

**Interpretacion**





### Room 15






### Room 16



